name: 'Hello world'
description: 'Greet someone and record the time'
Inputs:
  who-to-greet:
    description: 'Who to geet'
    required: 'true'
    defailt: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}